### ISSUE TITLE
No option for password change?

### ISSUE THREAD

**Issue by ThePiachu** [ripple/ripple-client#177]
I have looked around the website and I am unable to find an option to change my password. I have found a place that displays my password and secret key, but no option to change it.

r3AWbdp2jQLXLywJypdoNwVSvr81xs3uhn

**Comment by deed02392** [comment]
@melvincarvalho do you have any technical details about the localstorage db blobs? I am trying to figure out if I can recover my secret key from it?

**Comment by melvincarvalho** [comment]
Wow, this an old issue!  Im afraid I dont recall how to do this.  But your key should be in there somewhere.

**Comment by deed02392** [comment]
@melvincarvalho Indeed it is old, and plenty of time for the XRP to appreciate in value! It is a relief to know the key should be in there, is it encrypted though? Is there anywhere I can look to determine the structure of the data or is that code missing now because ripple.com/client is no longer?

**Comment by sublimator** [comment]
You used local storage option?

**Comment by melvincarvalho** [comment]
iirc it's encrypted using your password and username, so you need your password to decrypt -- it's a very old version of ripple client, try 2013

**Comment by sublimator** [comment]
Try saving the blob before you go messing around with potentially buggy
versions of the client.

It's encrypted yes.

**Comment by sublimator** [comment]
Few different schemes:
https://github.com/ripple/ripple-lib-java/blob/master/ripple-client/src/main/java/com/ripple/client/blobvault/BlobVault.java#L63-L75

**Comment by sublimator** [comment]
https://github.com/ripple/ripple-lib-java/blob/master/ripple-core/src/main/java/com/ripple/crypto/sjcljson/JSONEncrypt.java#L100

**Comment by deed02392** [comment]
@sublimator I'm not sure if I used the local storage option, it was so long ago :-( I guess I wouldn't have a 9K localstorage db file if I had not? And my username/pass combination don't seem to be working on the ripple trade migration form, so maybe that is also evidence I used the local storage option?

So hopefully with these code you're sharing with me, I will be able to reimplement ripple.com/client as it was back in the day and decrypt the local storage blobs, in which I will find the secret key I need to access the wallet from any Ripple client? I have made several copies of the sqlite file and marked the ones I'll test against as read only on the file system.

**Comment by sublimator** [comment]
Damn :/

Good luck

**Comment by deed02392** [comment]
Haha, that does not fill me with confidence. But thanks a lot for the links.

**Comment by sublimator** [comment]
I had a million XRP back in the day, sold just b4 Jed was dumping all the
time, haha

You still got some hope by the sounds.

**Comment by deed02392** [comment]
I'm sure there are going to be loads of stories like that in the coming days. Perhaps it is cryptocurrency that is how the [meek inherit the Earth](https://en.wikipedia.org/wiki/Matthew_5:5) sorry for the bible ref!

**Comment by sublimator** [comment]
Yeah, haha, curses on that guy for dumping. I never got around to  buying
back as I intended. Curses on me! lol

**Comment by deed02392** [comment]
I'll tell you the same thing I told my friend who had 100 BTC when they were £80 each and sold them at £100 each - even if you'd kept them longer, you probably would have only sold them at £110 or £120 each. If anything actually the only reason most people get rich from cryptocurrency is because they forgot they had any in the first place.

**Comment by sublimator** [comment]
haha, yeah, maybe, who knows :)

I don't know anything about trading and actually bought them just to hodl,
but
someone I respected told me to sell before the dump.

If and woulds eh
