### ISSUE TITLE
Usernames on Trade BIDS/ASKS

### ISSUE THREAD

**Issue by adaptive** [ripple/ripple-client#2114]
Case: USD/XRP Bitstamp 
Momentarily the addresses don't show their usernames, for each bid/ask. After an update they are shown, then disappear. I am checking addresses that effectively have username associated.

How does the system display when there are two address for the same bid?
##

**Comment by annatonger** [comment]
Can you clarify what part of the UI you are referring to? Screenshot, video or GIF will be helpful. Thanks!
