### ISSUE TITLE
Problem with login on 1.3.0

### ISSUE THREAD

**Issue by hynese** [ripple/ripple-client#2156]
So I'm using Google Chrome in Incognito mode (so as to disable all extensions).

I type in my username and password, then enter the 2FA code.

I'm then taken to a funny looking screen that's asking again for my 2FA code.

This happens on Firefox too. I thought it was AdBlock Plus (I also use Ghostery and Privacy Badger).

![Image of bug](http://i60.tinypic.com/1zl4vg2.png)

Other comments:
- page takes too long to load (the spinning Ripple logo is cool, but annoying after a while)
- On the 2FA login: I think the positioning/colouring of the "Send to SMS" button is wrong and needs to change. Too many times I've clicked on the SMS button by accident.
- I'd like to be able to convert 100% of my BTC to Ripple without having to guess what the current price is. The user interface is a little bit annoying.
- the page loading is very slow on Firefox (even with add-ons disabled)
- I like the ticker feature

I think these issues are important - the rippletrade.com page should (in my opinion) stink of high security and high quality. New people familiar with security and finance would get a very bad impression if this was their first visit to the site and they experienced these errors.

**Comment by vhpoet** [comment]
Thanks for the report. You can check the status on this issue on [Jira](https://ripplelabs.atlassian.net/browse/RT-3145). I agree with your comments, we're working on them.
