### ISSUE TITLE
Remove cash deposit info

### ISSUE THREAD

**Issue by mariatabach** [ripple/ripple-client#2270]
Hello. We stop to allow users making cash deposits. We need to remove all mentioning of cash deposits. We need to remove the option "Deposit cash at Bank of America branches" wherever those options appear. 
Instead of having options for Deposit:
                Deposit instantly via selected banks
                Deposit cash at Bank of America branches (3 business days)
                Deposit via online bank transfer (3 business days)

We need to have only
                Deposit instantly via selected banks
                Deposit via online bank transfer (3 business days)

**Comment by themusicgod1** [comment]
What happened with the cash deposits?

**Comment by mariatabach** [comment]
We do not allow them any more because of risks of fraud.

**Comment by MarkusTeufelberger** [comment]
Why is this part of the reference client anyways? This is/was a feature of a third party gateway (SnapSwap).
