### ISSUE TITLE
Offer shows at wrong price

### ISSUE THREAD

**Issue by JoelKatz** [ripple/ripple-client#2315]
![Wrong price](http://i.snag.gy/O77Ht.jpg)

Offer place at 140 XRP per PRO. Offer shows in orderbook as 139.10 XRP per PRO.

Raw order:
```
            "taker_gets" : "14000000000",
            "taker_pays" : {
               "currency" : "PRO",
               "issuer" : "rGh84RRDX4q6udARHpAA6Mq1v4rXqnzhRF",
               "value" : "100"
            }
```

The three offers shown in the image are the only offers in the entire order book, so it's not caused by combining offers.

Client version is 1.0.11-117
Logging out and back in results in the same display,.

The precise offer quality is 139.99999999999999720000000000000005, so no reason it should show as 139.100.

**Comment by JoelKatz** [comment]
Client version is 1.0.11-117

**Comment by vhpoet** [comment]
@JoelKatz 1.0.11 has been released 5 months ago, a lot of things changed since then. Please reopen the issue if it's happening on the latest version.
