### ISSUE TITLE
Duplicates in ng-repeat on /#/trade page (1.5.2)

### ISSUE THREAD

**Issue by kureus** [ripple/ripple-client#2566]
Chrome Version 43.0.2357.134 (64-bit), OSX 10.10.4
![screen shot 2015-07-17 at 11 27 13](https://cloud.githubusercontent.com/assets/385251/8745407/759104f6-2c77-11e5-941a-5cfeebc1b605.png)

**Comment by sublimator** [comment]
Did I read that right as that it's trying to order by BookDirectory ?

**Comment by kureus** [comment]
`Repeater: order in bookShow.bids track by order.BookDirectory`.

**Comment by sublimator** [comment]
That's definitely a bug, as there's a BookDirectory for every given
takerPays/takerGets ratio

I think it probably wants to be track by order.index

**Comment by kureus** [comment]
Ah yeah I can fix the BTC/BTC page by deleting my order which happened to contain the duplicate price. Blind QA testing there! Shall I submit a pull request to change track by to order.index or leave it to you guys?

**Comment by sublimator** [comment]
You can submit one if you like :) It's a good way of reporting the issue

(I'm only 99.9% sure that's the correct fix. I don't work on ripple-client)

**Comment by sublimator** [comment]
https://github.com/ripple/ripple-client/commit/797abf10d5ff8f46dbb61928c4f34c2ba8c3e0f7

It seemed intentional, I'm not sure the intent behind it

**Comment by sublimator** [comment]
maybe it collapses the bids/ask as a sum of the price ? i.e. it's doing a
group by BookDirectory somewhere else ? shrug

@vhpoet ?

**Comment by kureus** [comment]
@sublimator @vhpoet Just to add, in case you haven't experienced this, ripple client completely locks up when this bug occurrs. It's not entirely obvious from my screenshot but the ng-repeat gets stuck in an infinite loop and throws the same error indefinitely. So if you happen to place an order, or one already exists, with a duplicate price ripple client is unusable.  Could maybe be argued will only occur very rarely but if not its a showstopper imo

**Comment by sublimator** [comment]
Thanks Dan

**Comment by kureus** [comment]
Hey @sublimator, sorry to hijack this thread but even without this bug and after the maintenance outage/hardware upgrade of last week https://rippletrade.com/#/trade is still basically unusable for me. All 4 of my cpus start working like crazy, the fan kicks in and gigs of ram gets eaten very quickly. The page becomes barely responsive and I have to wait 5-10 seconds for a click to register and respond, if it even does at all.

I realise there is a bug tracker at https://ripplelabs.atlassian.net/secure/RapidBoard.jspa?rapidView=94&projectKey=RT, however I can't see any cards which would suggest such known poor performance. Seems to be mainly features and feature polish. Nor can I see lots of yet to be released commits, develop is currently only 7 ahead of master/release unlike say the 250 commits ripple-lib develop is ahead of release (maybe it's all being done in private repos?). It's also difficult to file a bug myself when I have basically nothing of substance to report! The only card I have found anywhere near is https://ripplelabs.atlassian.net/browse/RT-3184, entitled "Create logging software for to monitor client-side JS usage on RT", which would suggest you're trying to diagnose similar problems yourself or at the very least are aware of performance. 

I know you said you don't work on the ripple-client team but is there someone I could talk to or possibly even work with who does? I've CPU profiled the trade page and CPU profiled ripple charts. Considering they are both built on angular/d3, are using the same lib to call the same backend the difference is stark. One profile is largely idle and the other is just maxed out. I realise in ripple-client there is the large overhead of everything being account aware & the new crazy merging of autobridged/direct orderbooks in but even still.

I've tried posting in forums but I just get people agreeing that RT is slow/buggy which is useless to me!
I'd like to help diagnose or even fix the problems :-) I mainly work on top of ripple-lib but RT is very useful as an audit trail and exposing real time account state. If you can show me what I am missing or help me fix the problem or even just point me to someone else who I can talk too I would be most grateful.

**Comment by annatonger** [comment]
@darkdarkdragon - can you look into this?

**Comment by annatonger** [comment]
Thanks for the detailed bug report, btw!

**Comment by darkdarkdragon** [comment]
@annatonger of course.

**Comment by kureus** [comment]
Thanks for the reply, @darkdarkdragon is there a way we can chat/communicate?

**Comment by sublimator** [comment]
Hey Dan, sorry I just only saw your latest message :( but happy to see you
found someone to sort it out with :)

**Comment by kureus** [comment]
@sublimator No worries. Thanks for your help so far. I'm guessing you're on the ripple-lib team? May have a couple of questions for you too ;-)

**Comment by vhpoet** [comment]
@kureus hey, thanks for the detailed report. I did the change from `index` to `BookDirectory`. For some reason `index` was failing. We're combining same price orders so `BookDirectory` should've worked.. but I forgot that if the order is submitted by the current user it doesn't get merged with the same price orders.

**Comment by kureus** [comment]
Hey @vhpoet, thanks for your explanation of the original bug I posted. Unfortunately even when this bug isn't affecting me I find ripple-trade basically unusable (see my big post above). I was hoping to maybe talk to or even work a dev to try and triage this situation and find the root of the issues, as right now I just have a non responsive app with little clues as to why. Are none of your team seeing this? Does RT fly for you all on your machines?

**Comment by vhpoet** [comment]
@kureus is it only slow on one account? or is it on every account?

**Comment by kureus** [comment]
@vhpoet Multiple accounts. Are you thinking of a specific case imparticular that might be an issue?

Do you use RT, or do your tests replicate using RT, for any length of time? Sometimes RT can be just about usable for a few moments but then it seems as tho something gets "stuck" somehow. CPU goes to max, ram gets eaten but no errors are thrown. Gut instinct, a connection hangs somewhere and RT can't recover and doesn't throw. Thinking outloud there but that's what it feels like. There's one warning that gets thrown in the console which may back this up

    WebSocket connection to 'wss://s-west.ripple.com/' failed: WebSocket is closed before the connection is established.

coming out of server.js:363. Can you shed any light on that warning, and the context of it?

**Comment by kureus** [comment]
@vhpoet Any thoughts on my last comment?
