### ISSUE TITLE
RippleTrade address error

### ISSUE THREAD

**Issue by hxl9654** [ripple/ripple-client#2567]
When I try to send xrp to this address :skdkfjekcsdkdfkgxcmvnlmmoesdfgvvcdgfkjfv
The system ask me to send at least 20xrp. I tried.
XRP goes to rrrrrDfz2GcpxLbvg45eqHMZAefgsL9u.
And when I try again, send xrp to this address :skdkfjekcsdkdfkgxcmvnlmmoesdfgvvcdgfkjfv
The system ask me to send at least 20xrp again. I tried again. 
XRP goes to rrrrrDfz2GcpxLbvg45eqHMZAefgsL9u again.
And I ask my friend to test this.
He send xrp to this address :skdkfjekcsdkdfkgxcmvnlmmoesdfgvvcdgfkjfv
The system ask him to send at least 20xrp again.
XRP goes to rLQMMu3SBxcWWU1iPwRvcRwAu2wq2SSQZT
And he tested again.
He send xrp to this address :skdkfjekcsdkdfkgxcmvnlmmoesdfgvvcdgfkjfv
The system ask him to send at least 20xrp again.
XRP goes to rLQMMu3SBxcWWU1iPwRvcRwAu2wq2SSQZT
##

**Comment by qwgg9654** [comment]
So, this may be a address cheaking bug.
Or, it can be a address transform bug.
