### ISSUE TITLE
New Wallet Creation & Missing XRP

### ISSUE THREAD

**Issue by rippleNYC** [ripple/ripple-client#459]
Something weird happened a bit ago. 

I helped a friend set up a ripple wallet, I copied the newly created receiving address right after creation of the wallet, and sent 17,000 xrp to it. 

Then he had to reload, and log back in, because the XRP wasn't showing up for some reason.

Once he logged back in, the XRP had not arrived, and the receiving address was now different; Further, the address I sent to originally was a non-existent account prior to sending the 17000 to it. 

I checked the ripple.com/graph. Just wanted to tell you. I'm not sure what/how it happened. It wasn't a mistake on my part. I remembered the first bits from when the wallet was created. 

Anyways, perhaps something to do with the UI side address creation, caching, or some other thing.

Just a warning to others, make sure that you log back into the wallet after creation, to make sure that the address does not change between initial setup and first login, after you have explicitly logged out (top right).

**Comment by DanielTheGeek** [comment]
Hello, I can help recover the coins for a little profit after the work is done. Interested in this because in 2023 Ripple is now more valuable. I hope you're still alive though.
