### ISSUE TITLE
"You have to be online to see this screen"

### ISSUE THREAD

**Issue by Cingetorix** [ripple/ripple-client#551]
I've tried to log in a couple times this morning. So far, it won't let me see my balance or trade, and it states, "you have to be online to see this screen".  However, I have logged in correctly, and there is nothing wrong with my internet connection.

Thanks.

**Comment by SrinivasUppuluri** [comment]
> I've tried to log in a couple times this morning. So far, it won't let me see my balance or trade, and it states, "you have to be online to see this screen". However, I have logged in correctly, and there is nothing wrong with my internet connection.
> 
> Thanks.

Hi All: Before  you all try all of the detailed solutions & troubleshooting solutions below, you May want to Goto - Settings and There is a Check Box in there to be Online. I keep that Checked off, as it will ensure No connection when you dont really need it - You need the wallet to pull down or send out tokens - thats all. So Turn it on when you need to. That helps in my case , especially when I dont use the application for a while and forget that I had turned this off!
